#!/bin/bash

# Default values for config parameters
readonly DEF_TRANSPARENCY_ENABLED=1
readonly DEF_TRANSPARENCY_VALUE=0.85

[ -r "$HOME/.config/urxvtq.conf" ] && source "$HOME/.config/urxvtq.conf"

# Assing default values to unset variables
: "${TRANSPARENCY_ENABLED:=$DEF_TRANSPARENCY_ENABLED}"
: "${TRANSPARENCY_VALUE:=$DEF_TRANSPARENCY_VALUE}"

fix_position() {
    local wid="$1"
    xdotool windowmove --sync "$wid" x 0
    wmctrl -i -r "$wid" -b add,maximized_horz
    screen -S urxvtq -X redisplay
}

show_window() {
    local wid="$1"
    [ "$TRANSPARENCY_ENABLED" = 1 ] && \
        transset --id "$wid" "$TRANSPARENCY_VALUE" >/dev/null
    xdotool windowmap --sync "$wid"
    xdotool windowfocus --sync "$wid"
    fix_position "$wid"
}

hide_window() {
    local wid="$1"
    xdotool windowunmap --sync "$wid"
}

wid=$(xdotool search --classname urxvtq)
if [ -z "$wid" ]; then
    screen -d -m -S urxvtq -c %%DESTDIR%%/lib/urxvtq/screenrc
    if pgrep urxvtd >/dev/null; then
        _term=urxvtc
    else
        _term=urxvt
    fi
    $_term -name urxvtq +icon \
        -keysym.S-Next builtin-string: \
        -keysym.S-Prior builtin-string: \
        -e screen -r urxvtq
    wid=$(xdotool search --limit 1 --sync --classname urxvtq)
    show_window "$wid"
else
    if [ -z "$(xdotool search --onlyvisible --classname urxvtq)" ]; then
        show_window "$wid"
    else
        hide_window "$wid"
    fi
fi
